// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/category.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryID    int64                  `protobuf:"varint,1,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCategoryRequest) Reset() {
	*x = SaveCategoryRequest{}
	mi := &file_proto_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCategoryRequest) ProtoMessage() {}

func (x *SaveCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCategoryRequest.ProtoReflect.Descriptor instead.
func (*SaveCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_category_proto_rawDescGZIP(), []int{0}
}

func (x *SaveCategoryRequest) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *SaveCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SaveCategoryResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Success       bool                       `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SaveCategoryResponse_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCategoryResponse) Reset() {
	*x = SaveCategoryResponse{}
	mi := &file_proto_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCategoryResponse) ProtoMessage() {}

func (x *SaveCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCategoryResponse.ProtoReflect.Descriptor instead.
func (*SaveCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_category_proto_rawDescGZIP(), []int{1}
}

func (x *SaveCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SaveCategoryResponse) GetData() *SaveCategoryResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryID    int64                  `protobuf:"varint,1,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_proto_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_category_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteCategoryRequest) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_proto_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_category_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SaveCategoryResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCategoryResponse_Data) Reset() {
	*x = SaveCategoryResponse_Data{}
	mi := &file_proto_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCategoryResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCategoryResponse_Data) ProtoMessage() {}

func (x *SaveCategoryResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCategoryResponse_Data.ProtoReflect.Descriptor instead.
func (*SaveCategoryResponse_Data) Descriptor() ([]byte, []int) {
	return file_proto_category_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SaveCategoryResponse_Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_category_proto protoreflect.FileDescriptor

const file_proto_category_proto_rawDesc = "" +
	"\n" +
	"\x14proto/category.proto\x12\bcategory\"I\n" +
	"\x13SaveCategoryRequest\x12\x1e\n" +
	"\n" +
	"categoryID\x18\x01 \x01(\x03R\n" +
	"categoryID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9f\x01\n" +
	"\x14SaveCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2#.category.SaveCategoryResponse.DataR\x04data\x1a\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x15DeleteCategoryRequest\x12\x1e\n" +
	"\n" +
	"categoryID\x18\x01 \x01(\x03R\n" +
	"categoryID\"L\n" +
	"\x16DeleteCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb5\x01\n" +
	"\x0fCategoryService\x12M\n" +
	"\fSaveCategory\x12\x1d.category.SaveCategoryRequest\x1a\x1e.category.SaveCategoryResponse\x12S\n" +
	"\x0eDeleteCategory\x12\x1f.category.DeleteCategoryRequest\x1a .category.DeleteCategoryResponseB\x10Z\x0eproto/categoryb\x06proto3"

var (
	file_proto_category_proto_rawDescOnce sync.Once
	file_proto_category_proto_rawDescData []byte
)

func file_proto_category_proto_rawDescGZIP() []byte {
	file_proto_category_proto_rawDescOnce.Do(func() {
		file_proto_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_category_proto_rawDesc), len(file_proto_category_proto_rawDesc)))
	})
	return file_proto_category_proto_rawDescData
}

var file_proto_category_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_category_proto_goTypes = []any{
	(*SaveCategoryRequest)(nil),       // 0: category.SaveCategoryRequest
	(*SaveCategoryResponse)(nil),      // 1: category.SaveCategoryResponse
	(*DeleteCategoryRequest)(nil),     // 2: category.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),    // 3: category.DeleteCategoryResponse
	(*SaveCategoryResponse_Data)(nil), // 4: category.SaveCategoryResponse.Data
}
var file_proto_category_proto_depIdxs = []int32{
	4, // 0: category.SaveCategoryResponse.data:type_name -> category.SaveCategoryResponse.Data
	0, // 1: category.CategoryService.SaveCategory:input_type -> category.SaveCategoryRequest
	2, // 2: category.CategoryService.DeleteCategory:input_type -> category.DeleteCategoryRequest
	1, // 3: category.CategoryService.SaveCategory:output_type -> category.SaveCategoryResponse
	3, // 4: category.CategoryService.DeleteCategory:output_type -> category.DeleteCategoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_category_proto_init() }
func file_proto_category_proto_init() {
	if File_proto_category_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_category_proto_rawDesc), len(file_proto_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_category_proto_goTypes,
		DependencyIndexes: file_proto_category_proto_depIdxs,
		MessageInfos:      file_proto_category_proto_msgTypes,
	}.Build()
	File_proto_category_proto = out.File
	file_proto_category_proto_goTypes = nil
	file_proto_category_proto_depIdxs = nil
}
